# Generated by Django 5.0.6 on 2024-06-21 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('nature', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=256)),
                ('birth_year', models.IntegerField()),
                ('ethnicity', models.CharField(max_length=256)),
                ('parent_edu', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=512)),
                ('verbal_code', models.CharField(max_length=256)),
                ('post_status_opinion', models.CharField(max_length=256)),
                ('correctness', models.BooleanField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='researchdata.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='researchdata.user')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac1', models.IntegerField()),
                ('mac2', models.IntegerField()),
                ('mac3', models.IntegerField()),
                ('mac4', models.IntegerField()),
                ('mac5', models.IntegerField()),
                ('mac6', models.IntegerField()),
                ('mac7', models.IntegerField()),
                ('mac8', models.IntegerField()),
                ('mac9', models.IntegerField()),
                ('mac10', models.IntegerField()),
                ('mac11', models.IntegerField()),
                ('smds1', models.IntegerField()),
                ('smds2', models.IntegerField()),
                ('smds3', models.IntegerField()),
                ('smds4', models.IntegerField()),
                ('smds5', models.IntegerField()),
                ('smds6', models.IntegerField()),
                ('smds7', models.IntegerField()),
                ('smds8', models.IntegerField()),
                ('smds9', models.IntegerField()),
                ('smds10', models.IntegerField()),
                ('smds11', models.IntegerField()),
                ('smds12', models.IntegerField()),
                ('risk1', models.IntegerField()),
                ('risk2', models.IntegerField()),
                ('risk3', models.IntegerField()),
                ('risk4', models.IntegerField()),
                ('risk5', models.IntegerField()),
                ('risk6', models.IntegerField()),
                ('risk7', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.user')),
            ],
        ),
    ]
