# Generated by Django 5.0.6 on 2024-06-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.post'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.user'),
        ),
    ]
