# Generated by Django 5.0.6 on 2024-06-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002_alter_response_post_id_alter_response_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personality',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='user_id',
            new_name='user',
        ),
    ]
