# Generated by Django 5.0.6 on 2024-06-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0003_rename_user_id_personality_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='range',
            field=models.CharField(default="range", max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=512)),
                ('verbal_code', models.CharField(max_length=256)),
                ('assumption', models.CharField(max_length=256)),
                ('correctness', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
